apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl
  namespace: knativetutorial
spec:
  params:
    - description: The path to the yaml file to deploy within the git source
      name: pathToYamlFile
      type: string
    - description: Url of image repository
      name: imageUrl
      type: string
    - default: latest
      description: Tag of the images to be used.
      name: imageTag
      type: string
  resources:
    inputs:
      - name: git-source
        type: git
  steps:
    - args:
        - '-i'
        - '-e'
        - 's;__IMAGE__;$(inputs.params.imageUrl):$(inputs.params.imageTag);g'
        - /workspace/git-source/$(inputs.params.pathToYamlFile)
      command:
        - sed
      image: alpine
      name: update-yaml
      resources: {}
    - args:
        - apply
        - '-f'
        - /workspace/git-source/$(inputs.params.pathToYamlFile)
      command:
        - kubectl
      image: lachlanevenson/k8s-kubectl
      name: run-kubectl
      resources: {}

