apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: weather-service-eventlistener
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-weather-service-listener
    weight: 100
