apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: weather-service-listener
  namespace: knativetutorial
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: webhook-secret
              secretKey: secret
            eventTypes:
              - pull_request
              - push
      bindings:
        - name: weather-service-pipelinebinding
          ref: weather-service-pipelinebinding
      template:
        name: weather-service-triggertemplate
