apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: weather-service-pipelinebinding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: namespace
    value: knativetutorial
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: gitrepositoryname
    value: $(body.repository.name)
