apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image
  namespace: knativetutorial
spec:
  params:
    - name: url
      value: quay.io/jkeam/weather-service:latest
  type: image
