apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image
  namespace: knativetutorial
spec:
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/knativetutorial/weather-service:latest
  type: image

